// DO NOT EDIT.
// Generate with: go generate

package blend

import "testing"

func TestDrawFallbackNormal(t *testing.T)       { testDrawFallback(Normal{}, t) }
func TestDrawFallbackDarken(t *testing.T)       { testDrawFallback(Darken{}, t) }
func TestDrawFallbackMultiply(t *testing.T)     { testDrawFallback(Multiply{}, t) }
func TestDrawFallbackColorBurn(t *testing.T)    { testDrawFallback(ColorBurn{}, t) }
func TestDrawFallbackLinearBurn(t *testing.T)   { testDrawFallback(LinearBurn{}, t) }
func TestDrawFallbackDarkerColor(t *testing.T)  { testDrawFallback(DarkerColor{}, t) }
func TestDrawFallbackLighten(t *testing.T)      { testDrawFallback(Lighten{}, t) }
func TestDrawFallbackScreen(t *testing.T)       { testDrawFallback(Screen{}, t) }
func TestDrawFallbackColorDodge(t *testing.T)   { testDrawFallback(ColorDodge{}, t) }
func TestDrawFallbackLinearDodge(t *testing.T)  { testDrawFallback(LinearDodge{}, t) }
func TestDrawFallbackLighterColor(t *testing.T) { testDrawFallback(LighterColor{}, t) }
func TestDrawFallbackAdd(t *testing.T)          { testDrawFallback(Add{}, t) }
func TestDrawFallbackOverlay(t *testing.T)      { testDrawFallback(Overlay{}, t) }
func TestDrawFallbackSoftLight(t *testing.T)    { testDrawFallback(SoftLight{}, t) }
func TestDrawFallbackHardLight(t *testing.T)    { testDrawFallback(HardLight{}, t) }
func TestDrawFallbackLinearLight(t *testing.T)  { testDrawFallback(LinearLight{}, t) }
func TestDrawFallbackVividLight(t *testing.T)   { testDrawFallback(VividLight{}, t) }
func TestDrawFallbackPinLight(t *testing.T)     { testDrawFallback(PinLight{}, t) }
func TestDrawFallbackHardMix(t *testing.T)      { testDrawFallback(HardMix{}, t) }
func TestDrawFallbackDifference(t *testing.T)   { testDrawFallback(Difference{}, t) }
func TestDrawFallbackExclusion(t *testing.T)    { testDrawFallback(Exclusion{}, t) }
func TestDrawFallbackSubtract(t *testing.T)     { testDrawFallback(Subtract{}, t) }
func TestDrawFallbackDivide(t *testing.T)       { testDrawFallback(Divide{}, t) }
func TestDrawFallbackHue(t *testing.T)          { testDrawFallback(Hue{}, t) }
func TestDrawFallbackSaturation(t *testing.T)   { testDrawFallback(Saturation{}, t) }
func TestDrawFallbackColor(t *testing.T)        { testDrawFallback(Color{}, t) }
func TestDrawFallbackLuminosity(t *testing.T)   { testDrawFallback(Luminosity{}, t) }

func TestDrawNRGBAToNRGBANormal(t *testing.T)       { testDrawNRGBAToNRGBA(Normal{}, t) }
func TestDrawNRGBAToNRGBADarken(t *testing.T)       { testDrawNRGBAToNRGBA(Darken{}, t) }
func TestDrawNRGBAToNRGBAMultiply(t *testing.T)     { testDrawNRGBAToNRGBA(Multiply{}, t) }
func TestDrawNRGBAToNRGBAColorBurn(t *testing.T)    { testDrawNRGBAToNRGBA(ColorBurn{}, t) }
func TestDrawNRGBAToNRGBALinearBurn(t *testing.T)   { testDrawNRGBAToNRGBA(LinearBurn{}, t) }
func TestDrawNRGBAToNRGBADarkerColor(t *testing.T)  { testDrawNRGBAToNRGBA(DarkerColor{}, t) }
func TestDrawNRGBAToNRGBALighten(t *testing.T)      { testDrawNRGBAToNRGBA(Lighten{}, t) }
func TestDrawNRGBAToNRGBAScreen(t *testing.T)       { testDrawNRGBAToNRGBA(Screen{}, t) }
func TestDrawNRGBAToNRGBAColorDodge(t *testing.T)   { testDrawNRGBAToNRGBA(ColorDodge{}, t) }
func TestDrawNRGBAToNRGBALinearDodge(t *testing.T)  { testDrawNRGBAToNRGBA(LinearDodge{}, t) }
func TestDrawNRGBAToNRGBALighterColor(t *testing.T) { testDrawNRGBAToNRGBA(LighterColor{}, t) }
func TestDrawNRGBAToNRGBAAdd(t *testing.T)          { testDrawNRGBAToNRGBA(Add{}, t) }
func TestDrawNRGBAToNRGBAOverlay(t *testing.T)      { testDrawNRGBAToNRGBA(Overlay{}, t) }
func TestDrawNRGBAToNRGBASoftLight(t *testing.T)    { testDrawNRGBAToNRGBA(SoftLight{}, t) }
func TestDrawNRGBAToNRGBAHardLight(t *testing.T)    { testDrawNRGBAToNRGBA(HardLight{}, t) }
func TestDrawNRGBAToNRGBALinearLight(t *testing.T)  { testDrawNRGBAToNRGBA(LinearLight{}, t) }
func TestDrawNRGBAToNRGBAVividLight(t *testing.T)   { testDrawNRGBAToNRGBA(VividLight{}, t) }
func TestDrawNRGBAToNRGBAPinLight(t *testing.T)     { testDrawNRGBAToNRGBA(PinLight{}, t) }
func TestDrawNRGBAToNRGBAHardMix(t *testing.T)      { testDrawNRGBAToNRGBA(HardMix{}, t) }
func TestDrawNRGBAToNRGBADifference(t *testing.T)   { testDrawNRGBAToNRGBA(Difference{}, t) }
func TestDrawNRGBAToNRGBAExclusion(t *testing.T)    { testDrawNRGBAToNRGBA(Exclusion{}, t) }
func TestDrawNRGBAToNRGBASubtract(t *testing.T)     { testDrawNRGBAToNRGBA(Subtract{}, t) }
func TestDrawNRGBAToNRGBADivide(t *testing.T)       { testDrawNRGBAToNRGBA(Divide{}, t) }
func TestDrawNRGBAToNRGBAHue(t *testing.T)          { testDrawNRGBAToNRGBA(Hue{}, t) }
func TestDrawNRGBAToNRGBASaturation(t *testing.T)   { testDrawNRGBAToNRGBA(Saturation{}, t) }
func TestDrawNRGBAToNRGBAColor(t *testing.T)        { testDrawNRGBAToNRGBA(Color{}, t) }
func TestDrawNRGBAToNRGBALuminosity(t *testing.T)   { testDrawNRGBAToNRGBA(Luminosity{}, t) }

func TestDrawRGBAToNRGBANormal(t *testing.T)       { testDrawRGBAToNRGBA(Normal{}, t) }
func TestDrawRGBAToNRGBADarken(t *testing.T)       { testDrawRGBAToNRGBA(Darken{}, t) }
func TestDrawRGBAToNRGBAMultiply(t *testing.T)     { testDrawRGBAToNRGBA(Multiply{}, t) }
func TestDrawRGBAToNRGBAColorBurn(t *testing.T)    { testDrawRGBAToNRGBA(ColorBurn{}, t) }
func TestDrawRGBAToNRGBALinearBurn(t *testing.T)   { testDrawRGBAToNRGBA(LinearBurn{}, t) }
func TestDrawRGBAToNRGBADarkerColor(t *testing.T)  { testDrawRGBAToNRGBA(DarkerColor{}, t) }
func TestDrawRGBAToNRGBALighten(t *testing.T)      { testDrawRGBAToNRGBA(Lighten{}, t) }
func TestDrawRGBAToNRGBAScreen(t *testing.T)       { testDrawRGBAToNRGBA(Screen{}, t) }
func TestDrawRGBAToNRGBAColorDodge(t *testing.T)   { testDrawRGBAToNRGBA(ColorDodge{}, t) }
func TestDrawRGBAToNRGBALinearDodge(t *testing.T)  { testDrawRGBAToNRGBA(LinearDodge{}, t) }
func TestDrawRGBAToNRGBALighterColor(t *testing.T) { testDrawRGBAToNRGBA(LighterColor{}, t) }
func TestDrawRGBAToNRGBAAdd(t *testing.T)          { testDrawRGBAToNRGBA(Add{}, t) }
func TestDrawRGBAToNRGBAOverlay(t *testing.T)      { testDrawRGBAToNRGBA(Overlay{}, t) }
func TestDrawRGBAToNRGBASoftLight(t *testing.T)    { testDrawRGBAToNRGBA(SoftLight{}, t) }
func TestDrawRGBAToNRGBAHardLight(t *testing.T)    { testDrawRGBAToNRGBA(HardLight{}, t) }
func TestDrawRGBAToNRGBALinearLight(t *testing.T)  { testDrawRGBAToNRGBA(LinearLight{}, t) }
func TestDrawRGBAToNRGBAVividLight(t *testing.T)   { testDrawRGBAToNRGBA(VividLight{}, t) }
func TestDrawRGBAToNRGBAPinLight(t *testing.T)     { testDrawRGBAToNRGBA(PinLight{}, t) }
func TestDrawRGBAToNRGBAHardMix(t *testing.T)      { testDrawRGBAToNRGBA(HardMix{}, t) }
func TestDrawRGBAToNRGBADifference(t *testing.T)   { testDrawRGBAToNRGBA(Difference{}, t) }
func TestDrawRGBAToNRGBAExclusion(t *testing.T)    { testDrawRGBAToNRGBA(Exclusion{}, t) }
func TestDrawRGBAToNRGBASubtract(t *testing.T)     { testDrawRGBAToNRGBA(Subtract{}, t) }
func TestDrawRGBAToNRGBADivide(t *testing.T)       { testDrawRGBAToNRGBA(Divide{}, t) }
func TestDrawRGBAToNRGBAHue(t *testing.T)          { testDrawRGBAToNRGBA(Hue{}, t) }
func TestDrawRGBAToNRGBASaturation(t *testing.T)   { testDrawRGBAToNRGBA(Saturation{}, t) }
func TestDrawRGBAToNRGBAColor(t *testing.T)        { testDrawRGBAToNRGBA(Color{}, t) }
func TestDrawRGBAToNRGBALuminosity(t *testing.T)   { testDrawRGBAToNRGBA(Luminosity{}, t) }

func TestDrawNRGBAToRGBANormal(t *testing.T)       { testDrawNRGBAToRGBA(Normal{}, t) }
func TestDrawNRGBAToRGBADarken(t *testing.T)       { testDrawNRGBAToRGBA(Darken{}, t) }
func TestDrawNRGBAToRGBAMultiply(t *testing.T)     { testDrawNRGBAToRGBA(Multiply{}, t) }
func TestDrawNRGBAToRGBAColorBurn(t *testing.T)    { testDrawNRGBAToRGBA(ColorBurn{}, t) }
func TestDrawNRGBAToRGBALinearBurn(t *testing.T)   { testDrawNRGBAToRGBA(LinearBurn{}, t) }
func TestDrawNRGBAToRGBADarkerColor(t *testing.T)  { testDrawNRGBAToRGBA(DarkerColor{}, t) }
func TestDrawNRGBAToRGBALighten(t *testing.T)      { testDrawNRGBAToRGBA(Lighten{}, t) }
func TestDrawNRGBAToRGBAScreen(t *testing.T)       { testDrawNRGBAToRGBA(Screen{}, t) }
func TestDrawNRGBAToRGBAColorDodge(t *testing.T)   { testDrawNRGBAToRGBA(ColorDodge{}, t) }
func TestDrawNRGBAToRGBALinearDodge(t *testing.T)  { testDrawNRGBAToRGBA(LinearDodge{}, t) }
func TestDrawNRGBAToRGBALighterColor(t *testing.T) { testDrawNRGBAToRGBA(LighterColor{}, t) }
func TestDrawNRGBAToRGBAAdd(t *testing.T)          { testDrawNRGBAToRGBA(Add{}, t) }
func TestDrawNRGBAToRGBAOverlay(t *testing.T)      { testDrawNRGBAToRGBA(Overlay{}, t) }
func TestDrawNRGBAToRGBASoftLight(t *testing.T)    { testDrawNRGBAToRGBA(SoftLight{}, t) }
func TestDrawNRGBAToRGBAHardLight(t *testing.T)    { testDrawNRGBAToRGBA(HardLight{}, t) }
func TestDrawNRGBAToRGBALinearLight(t *testing.T)  { testDrawNRGBAToRGBA(LinearLight{}, t) }
func TestDrawNRGBAToRGBAVividLight(t *testing.T)   { testDrawNRGBAToRGBA(VividLight{}, t) }
func TestDrawNRGBAToRGBAPinLight(t *testing.T)     { testDrawNRGBAToRGBA(PinLight{}, t) }
func TestDrawNRGBAToRGBAHardMix(t *testing.T)      { testDrawNRGBAToRGBA(HardMix{}, t) }
func TestDrawNRGBAToRGBADifference(t *testing.T)   { testDrawNRGBAToRGBA(Difference{}, t) }
func TestDrawNRGBAToRGBAExclusion(t *testing.T)    { testDrawNRGBAToRGBA(Exclusion{}, t) }
func TestDrawNRGBAToRGBASubtract(t *testing.T)     { testDrawNRGBAToRGBA(Subtract{}, t) }
func TestDrawNRGBAToRGBADivide(t *testing.T)       { testDrawNRGBAToRGBA(Divide{}, t) }
func TestDrawNRGBAToRGBAHue(t *testing.T)          { testDrawNRGBAToRGBA(Hue{}, t) }
func TestDrawNRGBAToRGBASaturation(t *testing.T)   { testDrawNRGBAToRGBA(Saturation{}, t) }
func TestDrawNRGBAToRGBAColor(t *testing.T)        { testDrawNRGBAToRGBA(Color{}, t) }
func TestDrawNRGBAToRGBALuminosity(t *testing.T)   { testDrawNRGBAToRGBA(Luminosity{}, t) }

func TestDrawRGBAToRGBANormal(t *testing.T)       { testDrawRGBAToRGBA(Normal{}, t) }
func TestDrawRGBAToRGBADarken(t *testing.T)       { testDrawRGBAToRGBA(Darken{}, t) }
func TestDrawRGBAToRGBAMultiply(t *testing.T)     { testDrawRGBAToRGBA(Multiply{}, t) }
func TestDrawRGBAToRGBAColorBurn(t *testing.T)    { testDrawRGBAToRGBA(ColorBurn{}, t) }
func TestDrawRGBAToRGBALinearBurn(t *testing.T)   { testDrawRGBAToRGBA(LinearBurn{}, t) }
func TestDrawRGBAToRGBADarkerColor(t *testing.T)  { testDrawRGBAToRGBA(DarkerColor{}, t) }
func TestDrawRGBAToRGBALighten(t *testing.T)      { testDrawRGBAToRGBA(Lighten{}, t) }
func TestDrawRGBAToRGBAScreen(t *testing.T)       { testDrawRGBAToRGBA(Screen{}, t) }
func TestDrawRGBAToRGBAColorDodge(t *testing.T)   { testDrawRGBAToRGBA(ColorDodge{}, t) }
func TestDrawRGBAToRGBALinearDodge(t *testing.T)  { testDrawRGBAToRGBA(LinearDodge{}, t) }
func TestDrawRGBAToRGBALighterColor(t *testing.T) { testDrawRGBAToRGBA(LighterColor{}, t) }
func TestDrawRGBAToRGBAAdd(t *testing.T)          { testDrawRGBAToRGBA(Add{}, t) }
func TestDrawRGBAToRGBAOverlay(t *testing.T)      { testDrawRGBAToRGBA(Overlay{}, t) }
func TestDrawRGBAToRGBASoftLight(t *testing.T)    { testDrawRGBAToRGBA(SoftLight{}, t) }
func TestDrawRGBAToRGBAHardLight(t *testing.T)    { testDrawRGBAToRGBA(HardLight{}, t) }
func TestDrawRGBAToRGBALinearLight(t *testing.T)  { testDrawRGBAToRGBA(LinearLight{}, t) }
func TestDrawRGBAToRGBAVividLight(t *testing.T)   { testDrawRGBAToRGBA(VividLight{}, t) }
func TestDrawRGBAToRGBAPinLight(t *testing.T)     { testDrawRGBAToRGBA(PinLight{}, t) }
func TestDrawRGBAToRGBAHardMix(t *testing.T)      { testDrawRGBAToRGBA(HardMix{}, t) }
func TestDrawRGBAToRGBADifference(t *testing.T)   { testDrawRGBAToRGBA(Difference{}, t) }
func TestDrawRGBAToRGBAExclusion(t *testing.T)    { testDrawRGBAToRGBA(Exclusion{}, t) }
func TestDrawRGBAToRGBASubtract(t *testing.T)     { testDrawRGBAToRGBA(Subtract{}, t) }
func TestDrawRGBAToRGBADivide(t *testing.T)       { testDrawRGBAToRGBA(Divide{}, t) }
func TestDrawRGBAToRGBAHue(t *testing.T)          { testDrawRGBAToRGBA(Hue{}, t) }
func TestDrawRGBAToRGBASaturation(t *testing.T)   { testDrawRGBAToRGBA(Saturation{}, t) }
func TestDrawRGBAToRGBAColor(t *testing.T)        { testDrawRGBAToRGBA(Color{}, t) }
func TestDrawRGBAToRGBALuminosity(t *testing.T)   { testDrawRGBAToRGBA(Luminosity{}, t) }

func BenchmarkDrawFallbackNormal(b *testing.B)       { benchmarkDrawFallback(Normal{}, b) }
func BenchmarkDrawFallbackDarken(b *testing.B)       { benchmarkDrawFallback(Darken{}, b) }
func BenchmarkDrawFallbackMultiply(b *testing.B)     { benchmarkDrawFallback(Multiply{}, b) }
func BenchmarkDrawFallbackColorBurn(b *testing.B)    { benchmarkDrawFallback(ColorBurn{}, b) }
func BenchmarkDrawFallbackLinearBurn(b *testing.B)   { benchmarkDrawFallback(LinearBurn{}, b) }
func BenchmarkDrawFallbackDarkerColor(b *testing.B)  { benchmarkDrawFallback(DarkerColor{}, b) }
func BenchmarkDrawFallbackLighten(b *testing.B)      { benchmarkDrawFallback(Lighten{}, b) }
func BenchmarkDrawFallbackScreen(b *testing.B)       { benchmarkDrawFallback(Screen{}, b) }
func BenchmarkDrawFallbackColorDodge(b *testing.B)   { benchmarkDrawFallback(ColorDodge{}, b) }
func BenchmarkDrawFallbackLinearDodge(b *testing.B)  { benchmarkDrawFallback(LinearDodge{}, b) }
func BenchmarkDrawFallbackLighterColor(b *testing.B) { benchmarkDrawFallback(LighterColor{}, b) }
func BenchmarkDrawFallbackAdd(b *testing.B)          { benchmarkDrawFallback(Add{}, b) }
func BenchmarkDrawFallbackOverlay(b *testing.B)      { benchmarkDrawFallback(Overlay{}, b) }
func BenchmarkDrawFallbackSoftLight(b *testing.B)    { benchmarkDrawFallback(SoftLight{}, b) }
func BenchmarkDrawFallbackHardLight(b *testing.B)    { benchmarkDrawFallback(HardLight{}, b) }
func BenchmarkDrawFallbackLinearLight(b *testing.B)  { benchmarkDrawFallback(LinearLight{}, b) }
func BenchmarkDrawFallbackVividLight(b *testing.B)   { benchmarkDrawFallback(VividLight{}, b) }
func BenchmarkDrawFallbackPinLight(b *testing.B)     { benchmarkDrawFallback(PinLight{}, b) }
func BenchmarkDrawFallbackHardMix(b *testing.B)      { benchmarkDrawFallback(HardMix{}, b) }
func BenchmarkDrawFallbackDifference(b *testing.B)   { benchmarkDrawFallback(Difference{}, b) }
func BenchmarkDrawFallbackExclusion(b *testing.B)    { benchmarkDrawFallback(Exclusion{}, b) }
func BenchmarkDrawFallbackSubtract(b *testing.B)     { benchmarkDrawFallback(Subtract{}, b) }
func BenchmarkDrawFallbackDivide(b *testing.B)       { benchmarkDrawFallback(Divide{}, b) }
func BenchmarkDrawFallbackHue(b *testing.B)          { benchmarkDrawFallback(Hue{}, b) }
func BenchmarkDrawFallbackSaturation(b *testing.B)   { benchmarkDrawFallback(Saturation{}, b) }
func BenchmarkDrawFallbackColor(b *testing.B)        { benchmarkDrawFallback(Color{}, b) }
func BenchmarkDrawFallbackLuminosity(b *testing.B)   { benchmarkDrawFallback(Luminosity{}, b) }

func BenchmarkDrawNRGBAToNRGBANormal(b *testing.B)       { benchmarkDrawNRGBAToNRGBA(Normal{}, b) }
func BenchmarkDrawNRGBAToNRGBADarken(b *testing.B)       { benchmarkDrawNRGBAToNRGBA(Darken{}, b) }
func BenchmarkDrawNRGBAToNRGBAMultiply(b *testing.B)     { benchmarkDrawNRGBAToNRGBA(Multiply{}, b) }
func BenchmarkDrawNRGBAToNRGBAColorBurn(b *testing.B)    { benchmarkDrawNRGBAToNRGBA(ColorBurn{}, b) }
func BenchmarkDrawNRGBAToNRGBALinearBurn(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(LinearBurn{}, b) }
func BenchmarkDrawNRGBAToNRGBADarkerColor(b *testing.B)  { benchmarkDrawNRGBAToNRGBA(DarkerColor{}, b) }
func BenchmarkDrawNRGBAToNRGBALighten(b *testing.B)      { benchmarkDrawNRGBAToNRGBA(Lighten{}, b) }
func BenchmarkDrawNRGBAToNRGBAScreen(b *testing.B)       { benchmarkDrawNRGBAToNRGBA(Screen{}, b) }
func BenchmarkDrawNRGBAToNRGBAColorDodge(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(ColorDodge{}, b) }
func BenchmarkDrawNRGBAToNRGBALinearDodge(b *testing.B)  { benchmarkDrawNRGBAToNRGBA(LinearDodge{}, b) }
func BenchmarkDrawNRGBAToNRGBALighterColor(b *testing.B) { benchmarkDrawNRGBAToNRGBA(LighterColor{}, b) }
func BenchmarkDrawNRGBAToNRGBAAdd(b *testing.B)          { benchmarkDrawNRGBAToNRGBA(Add{}, b) }
func BenchmarkDrawNRGBAToNRGBAOverlay(b *testing.B)      { benchmarkDrawNRGBAToNRGBA(Overlay{}, b) }
func BenchmarkDrawNRGBAToNRGBASoftLight(b *testing.B)    { benchmarkDrawNRGBAToNRGBA(SoftLight{}, b) }
func BenchmarkDrawNRGBAToNRGBAHardLight(b *testing.B)    { benchmarkDrawNRGBAToNRGBA(HardLight{}, b) }
func BenchmarkDrawNRGBAToNRGBALinearLight(b *testing.B)  { benchmarkDrawNRGBAToNRGBA(LinearLight{}, b) }
func BenchmarkDrawNRGBAToNRGBAVividLight(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(VividLight{}, b) }
func BenchmarkDrawNRGBAToNRGBAPinLight(b *testing.B)     { benchmarkDrawNRGBAToNRGBA(PinLight{}, b) }
func BenchmarkDrawNRGBAToNRGBAHardMix(b *testing.B)      { benchmarkDrawNRGBAToNRGBA(HardMix{}, b) }
func BenchmarkDrawNRGBAToNRGBADifference(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(Difference{}, b) }
func BenchmarkDrawNRGBAToNRGBAExclusion(b *testing.B)    { benchmarkDrawNRGBAToNRGBA(Exclusion{}, b) }
func BenchmarkDrawNRGBAToNRGBASubtract(b *testing.B)     { benchmarkDrawNRGBAToNRGBA(Subtract{}, b) }
func BenchmarkDrawNRGBAToNRGBADivide(b *testing.B)       { benchmarkDrawNRGBAToNRGBA(Divide{}, b) }
func BenchmarkDrawNRGBAToNRGBAHue(b *testing.B)          { benchmarkDrawNRGBAToNRGBA(Hue{}, b) }
func BenchmarkDrawNRGBAToNRGBASaturation(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(Saturation{}, b) }
func BenchmarkDrawNRGBAToNRGBAColor(b *testing.B)        { benchmarkDrawNRGBAToNRGBA(Color{}, b) }
func BenchmarkDrawNRGBAToNRGBALuminosity(b *testing.B)   { benchmarkDrawNRGBAToNRGBA(Luminosity{}, b) }

func BenchmarkDrawRGBAToNRGBANormal(b *testing.B)       { benchmarkDrawRGBAToNRGBA(Normal{}, b) }
func BenchmarkDrawRGBAToNRGBADarken(b *testing.B)       { benchmarkDrawRGBAToNRGBA(Darken{}, b) }
func BenchmarkDrawRGBAToNRGBAMultiply(b *testing.B)     { benchmarkDrawRGBAToNRGBA(Multiply{}, b) }
func BenchmarkDrawRGBAToNRGBAColorBurn(b *testing.B)    { benchmarkDrawRGBAToNRGBA(ColorBurn{}, b) }
func BenchmarkDrawRGBAToNRGBALinearBurn(b *testing.B)   { benchmarkDrawRGBAToNRGBA(LinearBurn{}, b) }
func BenchmarkDrawRGBAToNRGBADarkerColor(b *testing.B)  { benchmarkDrawRGBAToNRGBA(DarkerColor{}, b) }
func BenchmarkDrawRGBAToNRGBALighten(b *testing.B)      { benchmarkDrawRGBAToNRGBA(Lighten{}, b) }
func BenchmarkDrawRGBAToNRGBAScreen(b *testing.B)       { benchmarkDrawRGBAToNRGBA(Screen{}, b) }
func BenchmarkDrawRGBAToNRGBAColorDodge(b *testing.B)   { benchmarkDrawRGBAToNRGBA(ColorDodge{}, b) }
func BenchmarkDrawRGBAToNRGBALinearDodge(b *testing.B)  { benchmarkDrawRGBAToNRGBA(LinearDodge{}, b) }
func BenchmarkDrawRGBAToNRGBALighterColor(b *testing.B) { benchmarkDrawRGBAToNRGBA(LighterColor{}, b) }
func BenchmarkDrawRGBAToNRGBAAdd(b *testing.B)          { benchmarkDrawRGBAToNRGBA(Add{}, b) }
func BenchmarkDrawRGBAToNRGBAOverlay(b *testing.B)      { benchmarkDrawRGBAToNRGBA(Overlay{}, b) }
func BenchmarkDrawRGBAToNRGBASoftLight(b *testing.B)    { benchmarkDrawRGBAToNRGBA(SoftLight{}, b) }
func BenchmarkDrawRGBAToNRGBAHardLight(b *testing.B)    { benchmarkDrawRGBAToNRGBA(HardLight{}, b) }
func BenchmarkDrawRGBAToNRGBALinearLight(b *testing.B)  { benchmarkDrawRGBAToNRGBA(LinearLight{}, b) }
func BenchmarkDrawRGBAToNRGBAVividLight(b *testing.B)   { benchmarkDrawRGBAToNRGBA(VividLight{}, b) }
func BenchmarkDrawRGBAToNRGBAPinLight(b *testing.B)     { benchmarkDrawRGBAToNRGBA(PinLight{}, b) }
func BenchmarkDrawRGBAToNRGBAHardMix(b *testing.B)      { benchmarkDrawRGBAToNRGBA(HardMix{}, b) }
func BenchmarkDrawRGBAToNRGBADifference(b *testing.B)   { benchmarkDrawRGBAToNRGBA(Difference{}, b) }
func BenchmarkDrawRGBAToNRGBAExclusion(b *testing.B)    { benchmarkDrawRGBAToNRGBA(Exclusion{}, b) }
func BenchmarkDrawRGBAToNRGBASubtract(b *testing.B)     { benchmarkDrawRGBAToNRGBA(Subtract{}, b) }
func BenchmarkDrawRGBAToNRGBADivide(b *testing.B)       { benchmarkDrawRGBAToNRGBA(Divide{}, b) }
func BenchmarkDrawRGBAToNRGBAHue(b *testing.B)          { benchmarkDrawRGBAToNRGBA(Hue{}, b) }
func BenchmarkDrawRGBAToNRGBASaturation(b *testing.B)   { benchmarkDrawRGBAToNRGBA(Saturation{}, b) }
func BenchmarkDrawRGBAToNRGBAColor(b *testing.B)        { benchmarkDrawRGBAToNRGBA(Color{}, b) }
func BenchmarkDrawRGBAToNRGBALuminosity(b *testing.B)   { benchmarkDrawRGBAToNRGBA(Luminosity{}, b) }

func BenchmarkDrawNRGBAToRGBANormal(b *testing.B)       { benchmarkDrawNRGBAToRGBA(Normal{}, b) }
func BenchmarkDrawNRGBAToRGBADarken(b *testing.B)       { benchmarkDrawNRGBAToRGBA(Darken{}, b) }
func BenchmarkDrawNRGBAToRGBAMultiply(b *testing.B)     { benchmarkDrawNRGBAToRGBA(Multiply{}, b) }
func BenchmarkDrawNRGBAToRGBAColorBurn(b *testing.B)    { benchmarkDrawNRGBAToRGBA(ColorBurn{}, b) }
func BenchmarkDrawNRGBAToRGBALinearBurn(b *testing.B)   { benchmarkDrawNRGBAToRGBA(LinearBurn{}, b) }
func BenchmarkDrawNRGBAToRGBADarkerColor(b *testing.B)  { benchmarkDrawNRGBAToRGBA(DarkerColor{}, b) }
func BenchmarkDrawNRGBAToRGBALighten(b *testing.B)      { benchmarkDrawNRGBAToRGBA(Lighten{}, b) }
func BenchmarkDrawNRGBAToRGBAScreen(b *testing.B)       { benchmarkDrawNRGBAToRGBA(Screen{}, b) }
func BenchmarkDrawNRGBAToRGBAColorDodge(b *testing.B)   { benchmarkDrawNRGBAToRGBA(ColorDodge{}, b) }
func BenchmarkDrawNRGBAToRGBALinearDodge(b *testing.B)  { benchmarkDrawNRGBAToRGBA(LinearDodge{}, b) }
func BenchmarkDrawNRGBAToRGBALighterColor(b *testing.B) { benchmarkDrawNRGBAToRGBA(LighterColor{}, b) }
func BenchmarkDrawNRGBAToRGBAAdd(b *testing.B)          { benchmarkDrawNRGBAToRGBA(Add{}, b) }
func BenchmarkDrawNRGBAToRGBAOverlay(b *testing.B)      { benchmarkDrawNRGBAToRGBA(Overlay{}, b) }
func BenchmarkDrawNRGBAToRGBASoftLight(b *testing.B)    { benchmarkDrawNRGBAToRGBA(SoftLight{}, b) }
func BenchmarkDrawNRGBAToRGBAHardLight(b *testing.B)    { benchmarkDrawNRGBAToRGBA(HardLight{}, b) }
func BenchmarkDrawNRGBAToRGBALinearLight(b *testing.B)  { benchmarkDrawNRGBAToRGBA(LinearLight{}, b) }
func BenchmarkDrawNRGBAToRGBAVividLight(b *testing.B)   { benchmarkDrawNRGBAToRGBA(VividLight{}, b) }
func BenchmarkDrawNRGBAToRGBAPinLight(b *testing.B)     { benchmarkDrawNRGBAToRGBA(PinLight{}, b) }
func BenchmarkDrawNRGBAToRGBAHardMix(b *testing.B)      { benchmarkDrawNRGBAToRGBA(HardMix{}, b) }
func BenchmarkDrawNRGBAToRGBADifference(b *testing.B)   { benchmarkDrawNRGBAToRGBA(Difference{}, b) }
func BenchmarkDrawNRGBAToRGBAExclusion(b *testing.B)    { benchmarkDrawNRGBAToRGBA(Exclusion{}, b) }
func BenchmarkDrawNRGBAToRGBASubtract(b *testing.B)     { benchmarkDrawNRGBAToRGBA(Subtract{}, b) }
func BenchmarkDrawNRGBAToRGBADivide(b *testing.B)       { benchmarkDrawNRGBAToRGBA(Divide{}, b) }
func BenchmarkDrawNRGBAToRGBAHue(b *testing.B)          { benchmarkDrawNRGBAToRGBA(Hue{}, b) }
func BenchmarkDrawNRGBAToRGBASaturation(b *testing.B)   { benchmarkDrawNRGBAToRGBA(Saturation{}, b) }
func BenchmarkDrawNRGBAToRGBAColor(b *testing.B)        { benchmarkDrawNRGBAToRGBA(Color{}, b) }
func BenchmarkDrawNRGBAToRGBALuminosity(b *testing.B)   { benchmarkDrawNRGBAToRGBA(Luminosity{}, b) }

func BenchmarkDrawRGBAToRGBANormal(b *testing.B)       { benchmarkDrawRGBAToRGBA(Normal{}, b) }
func BenchmarkDrawRGBAToRGBADarken(b *testing.B)       { benchmarkDrawRGBAToRGBA(Darken{}, b) }
func BenchmarkDrawRGBAToRGBAMultiply(b *testing.B)     { benchmarkDrawRGBAToRGBA(Multiply{}, b) }
func BenchmarkDrawRGBAToRGBAColorBurn(b *testing.B)    { benchmarkDrawRGBAToRGBA(ColorBurn{}, b) }
func BenchmarkDrawRGBAToRGBALinearBurn(b *testing.B)   { benchmarkDrawRGBAToRGBA(LinearBurn{}, b) }
func BenchmarkDrawRGBAToRGBADarkerColor(b *testing.B)  { benchmarkDrawRGBAToRGBA(DarkerColor{}, b) }
func BenchmarkDrawRGBAToRGBALighten(b *testing.B)      { benchmarkDrawRGBAToRGBA(Lighten{}, b) }
func BenchmarkDrawRGBAToRGBAScreen(b *testing.B)       { benchmarkDrawRGBAToRGBA(Screen{}, b) }
func BenchmarkDrawRGBAToRGBAColorDodge(b *testing.B)   { benchmarkDrawRGBAToRGBA(ColorDodge{}, b) }
func BenchmarkDrawRGBAToRGBALinearDodge(b *testing.B)  { benchmarkDrawRGBAToRGBA(LinearDodge{}, b) }
func BenchmarkDrawRGBAToRGBALighterColor(b *testing.B) { benchmarkDrawRGBAToRGBA(LighterColor{}, b) }
func BenchmarkDrawRGBAToRGBAAdd(b *testing.B)          { benchmarkDrawRGBAToRGBA(Add{}, b) }
func BenchmarkDrawRGBAToRGBAOverlay(b *testing.B)      { benchmarkDrawRGBAToRGBA(Overlay{}, b) }
func BenchmarkDrawRGBAToRGBASoftLight(b *testing.B)    { benchmarkDrawRGBAToRGBA(SoftLight{}, b) }
func BenchmarkDrawRGBAToRGBAHardLight(b *testing.B)    { benchmarkDrawRGBAToRGBA(HardLight{}, b) }
func BenchmarkDrawRGBAToRGBALinearLight(b *testing.B)  { benchmarkDrawRGBAToRGBA(LinearLight{}, b) }
func BenchmarkDrawRGBAToRGBAVividLight(b *testing.B)   { benchmarkDrawRGBAToRGBA(VividLight{}, b) }
func BenchmarkDrawRGBAToRGBAPinLight(b *testing.B)     { benchmarkDrawRGBAToRGBA(PinLight{}, b) }
func BenchmarkDrawRGBAToRGBAHardMix(b *testing.B)      { benchmarkDrawRGBAToRGBA(HardMix{}, b) }
func BenchmarkDrawRGBAToRGBADifference(b *testing.B)   { benchmarkDrawRGBAToRGBA(Difference{}, b) }
func BenchmarkDrawRGBAToRGBAExclusion(b *testing.B)    { benchmarkDrawRGBAToRGBA(Exclusion{}, b) }
func BenchmarkDrawRGBAToRGBASubtract(b *testing.B)     { benchmarkDrawRGBAToRGBA(Subtract{}, b) }
func BenchmarkDrawRGBAToRGBADivide(b *testing.B)       { benchmarkDrawRGBAToRGBA(Divide{}, b) }
func BenchmarkDrawRGBAToRGBAHue(b *testing.B)          { benchmarkDrawRGBAToRGBA(Hue{}, b) }
func BenchmarkDrawRGBAToRGBASaturation(b *testing.B)   { benchmarkDrawRGBAToRGBA(Saturation{}, b) }
func BenchmarkDrawRGBAToRGBAColor(b *testing.B)        { benchmarkDrawRGBAToRGBA(Color{}, b) }
func BenchmarkDrawRGBAToRGBALuminosity(b *testing.B)   { benchmarkDrawRGBAToRGBA(Luminosity{}, b) }
